# Generated by Django 4.1.5 on 2023-03-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
    ]
