# Generated by Django 4.1.5 on 2023-04-08 11:01

import New_Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0006_customer_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('user',), 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=New_Shop.models.upload_location_customer, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='customer',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
