# Generated by Django 4.1.5 on 2023-04-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0008_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('customer',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
