# Generated by Django 4.1.5 on 2023-04-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0009_alter_orders_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
