# Generated by Django 4.1.5 on 2023-04-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0010_alter_customer_address_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
