# Generated by Django 4.1.5 on 2023-04-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0011_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
