# Generated by Django 4.1.5 on 2023-04-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0013_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='code',
        ),
    ]
