# Generated by Django 4.1.5 on 2023-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Shop', '0014_remove_promocode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='code',
            field=models.CharField(default='code', max_length=20, unique=True),
        ),
    ]
